<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>doctorSIM Test</title>
        <style>
            body {
                width: 100%;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #2EA6DE;
                letter-spacing: -3px;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }

            pre {
                font-family: "Consolas", monospace;
            }

            code {
                text-align: left;
                width: 90%;
                max-width: 600px;
            }
        </style>
    </head>
    <body>
        <h1>doctorSIM Test</h1>
        <h2>url parser...</h2>

        <?php if (isset($parsedUrl)) : ?>
            <pre><code><?php echo $parsedUrl ?></code></pre>
        <?php endif; ?>
    </body>
</html>
